### ISSUE TITLE
Web version of statnetWeb MCMC diagnostics not loading lattice plots correctly

### ISSUE THREAD

**Issue by smjenness** [statnet/statnetWeb#55] opened 2015-09-08 08:36 UTC
<img width="1269" alt="screen shot 2015-09-08 at 10 35 32 am" src="https://cloud.githubusercontent.com/assets/2521570/9730229/6aa8465e-5615-11e5-95d6-58b6c454fe18.png">

**Comment by martinamorris** [comment] 2015-09-08 13:01
I'm also not seeing what the problem is in the latticeplot MCMC 
diagnostic screenshot you uploaded.  (sorry if i'm missing something 
obvious)

On Tue, 8 Sep 2015, Samuel Jenness wrote:

> 
> screen shot 2015-09-08 at 10 35 32 am
> 
> —
> Reply to this email directly or view it on GitHub.[AH0J4k6G0dT4o2yLXPuNgBFpkzVbrX4Vks5ovpV-gaJpZM4F5VUS.gif]
> 
> 
>

****************************************************************
  Professor of Sociology and Statistics
  Director, UWCFAR Sociobehavioral and Prevention Research Core
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by smjenness** [comment] 2015-09-08 13:11
Compare to Slide 34 here:
http://statnet.github.io/nme/d2-s1.pdf

**Comment by martinamorris** [comment] 2015-09-08 13:16
so, missing the blue color, and using a histogram instead of the 
continuous distn for the edges?

On Tue, 8 Sep 2015, Samuel Jenness wrote:

> 
> Compare to Slide 34 here:
> http://statnet.github.io/nme/d2-s1.pdf
> 
> —
> Reply to this email directly or view it on GitHub.[AH0J4q-rsIA3XFdIU2HS8LVbbzul-YBwks5ovtXngaJpZM4F5VUS.gif]
> 
> 
>

****************************************************************
  Professor of Sociology and Statistics
  Director, UWCFAR Sociobehavioral and Prevention Research Core
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by smjenness** [comment] 2015-09-08 13:23
Sorry, let me be more precise: ergm has the suggested package lattice, which is used by mcmc.diagnostics to generate the two panel plots of MCMC mixing and the final distribution shape. When that package is not loaded correctly, ergm defaults to use the base plotting methods (screen shot from above); the difference is mainly cosmetic but did raise some confusion about differences between the slides in the workshop.

**Comment by ebey** [comment] 2015-09-08 18:25
Thanks. Moving the lattice packages to Imports so that they will be installed with the statnetWeb package. This will take effect with the next CRAN release.

**Closed** 2015-09-08 23:42 UTC
